# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Java CI

on: [push, pull_request]

jobs:
  build:

    #strategy:
    #  matrix:
    #    os: [ubuntu-latest, windows-latest, macOS-latest]
    #    java: [8, 11, 14]
    #  fail-fast: false
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [8, 11, 14]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up cache for ~./m2/repository
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: maven-${{ matrix.os }}-java${{ matrix.java }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ matrix.os }}-java${{ matrix.java }}-
            maven-${{ matrix.os }}-

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Build with Maven
        run: mvn verify -e -B -V -DdistributionFileName=apache-maven

      - name: Upload built Maven
        uses: actions/upload-artifact@v2
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.java == '11' }}
        with:
          name: built-maven
          path: apache-maven/target/

  integration-test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Collect environment context variables
        shell: bash
        run: |
          echo "::set-env name=REPO_BRANCH::${GITHUB_REF#refs/heads/}"
          echo "::set-env name=REPO_USER::${GITHUB_REPOSITORY%/*}"

      - name: Checkout feature branch on the forked maven-integration-testing repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.REPO_USER }}/maven-integration-testing
          path: maven-integration-testing/
          ref: ${{ env.REPO_BRANCH }}

      - name: Checkout master branch on the apache/maven-integration-testing repo
        uses: actions/checkout@v2
        if: failure()
        with:
          repository: apache/maven-integration-testing
          path: maven-integration-testing/

# TODO - split up integration test setup from the actual build

      - name: Download built Maven
        uses: actions/download-artifact@v2
        if: always()
        with:
          name: built-maven
          path: built-maven/

# TODO - Remove
      - name: debug ls
        if: always()
        run: ls -laSh built-maven/

# TODO - Remove
      - name: debug ls
        if: always()
        run: ls -laSh $GITHUB_WORKSPACE

      - name: Running integration tests
        if: always()
        run: mvn install -e -B -V -Prun-its,embedded -Dmaven.repo.local=$GITHUB_WORKSPACE/repo/ -DmavenDistro="$GITHUB_WORKSPACE/built-maven/apache-maven-bin.zip" -DwrapperDistroDir="$GITHUB_WORKSPACE/built-maven/" -f maven-integration-testing/pom.xml